// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWZQ4EEBpUAWoGhE-v0sPPnsHHqq1uOhA',
    appId: '1:613072666679:web:82cfe6a65a380fdaf6bfb2',
    messagingSenderId: '613072666679',
    projectId: 'appfoods-1e5ad',
    authDomain: 'appfoods-1e5ad.firebaseapp.com',
    storageBucket: 'appfoods-1e5ad.firebasestorage.app',
    measurementId: 'G-GTJ0NKCWGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsszXjN-wZAdx2ITXT_gBM7fZbKsHDck',
    appId: '1:613072666679:android:a1541549e576e1f6f6bfb2',
    messagingSenderId: '613072666679',
    projectId: 'appfoods-1e5ad',
    storageBucket: 'appfoods-1e5ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHWZcbwo3Rk-b-RVr3Pf5Kx44iIrNHZxw',
    appId: '1:613072666679:ios:8afb0ca567e980dcf6bfb2',
    messagingSenderId: '613072666679',
    projectId: 'appfoods-1e5ad',
    storageBucket: 'appfoods-1e5ad.firebasestorage.app',
    iosClientId: '613072666679-oc39kbd8glcqakh3tc0ev8mdolv0e9q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHWZcbwo3Rk-b-RVr3Pf5Kx44iIrNHZxw',
    appId: '1:613072666679:ios:8afb0ca567e980dcf6bfb2',
    messagingSenderId: '613072666679',
    projectId: 'appfoods-1e5ad',
    storageBucket: 'appfoods-1e5ad.firebasestorage.app',
    iosClientId: '613072666679-oc39kbd8glcqakh3tc0ev8mdolv0e9q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWZQ4EEBpUAWoGhE-v0sPPnsHHqq1uOhA',
    appId: '1:613072666679:web:c5247a3675c5d5d7f6bfb2',
    messagingSenderId: '613072666679',
    projectId: 'appfoods-1e5ad',
    authDomain: 'appfoods-1e5ad.firebaseapp.com',
    storageBucket: 'appfoods-1e5ad.firebasestorage.app',
    measurementId: 'G-Z6GHZ4SLV3',
  );
}
